extern zend_class_entry *php_midgard_query_storage_class;

PHP_MINIT_FUNCTION(midgard2_query_storage);
PHP_MINIT_FUNCTION(midgard2_query_holders);
PHP_MINIT_FUNCTION(midgard2_query_constraints);
PHP_MINIT_FUNCTION(midgard2_query_executors);
